import 'dart:convert';
import 'dart:io';

import 'package:args/command_runner.dart';
import 'package:cli_kit/cli_kit.dart';
import 'package:path/path.dart' as p;
import 'package:xcross/src/cli/ide/subcommands/vscode_json_merge.dart';
import 'package:xcross/src/cli/ide/xcross_executable.dart';
import 'package:xcross/src/errors.dart';

/// `xcross ide vscode` — write / upsert `.vscode/` so Run & Debug / Restart /
/// Hot Reload drive `xcross flutter run` (or `xcross dn run` in a DartNative
/// project — the DAP picks the subcommand from the project's pubspec).
final class VscodeCommand extends Command<void> {
  @override
  String get name => 'vscode';

  @override
  String get description =>
      'Set up .vscode/ so F5, Restart and Hot Reload run on an iOS device.';

  @override
  Future<void> run() async {
    final dir = Directory(p.join(Directory.current.path, '.vscode'));
    await dir.create(recursive: true);

    await _writeShim(dir);
    await upsertJsonFile(
      p.join(dir.path, 'launch.json'),
      (existing) => VscodeJsonMerge.mergeLaunchDoc(
        existing,
        generatedEnvironment: generatedIdeEnvironment,
      ),
    );
    await upsertJsonFile(
      p.join(dir.path, 'settings.json'),
      VscodeJsonMerge.mergeSettingsDoc,
    );

    Log.logInfo(
      'Next',
      Log.dim(
        'open the project in VS Code and press F5, '
        "then 'Hot Reload' / 'Restart' in the debug toolbar",
      ),
    );
  }

  /// The shim is always ours, so it is overwritten rather than merged.
  static Future<void> _writeShim(Directory dir) async {
    final exe = resolveXcrossExecutable(
      subcommand: 'vscode',
      brokenFeature: 'F5',
    );
    final shim = File(p.join(dir.path, 'xcross_dap.dart'));
    // The shim embeds the path as a non-raw Dart string literal, so `$` needs
    // escaping on top of what jsonEncode does.
    await shim.writeAsString(
      _shim
          .replaceAll('<XCROSS>', jsonEncode(exe).replaceAll(r'$', r'\$'))
          .replaceAll(
            '<ENVIRONMENT>',
            jsonEncode(generatedIdeEnvironment).replaceAll(r'$', r'\$'),
          )
          .replaceAll('<INHERIT_PARENT>', '$inheritIdeParentEnvironment'),
    );
    Log.logDone('Wrote ${p.relative(shim.path)}');
  }

  /// Read-merge-write a JSON/JSONC file. Skips the write when already current.
  static Future<void> upsertJsonFile(
    String path,
    Map<String, Object?> Function(Map<String, Object?>? existing) merge,
  ) async {
    final file = File(path);
    final existing = file.existsSync()
        ? _decodeJsonObject(await file.readAsString(), path)
        : null;

    final merged = merge(existing);
    if (existing != null && VscodeJsonMerge.jsonDeepEqual(existing, merged)) {
      Log.logDone('Unchanged ${p.relative(path)}');
      return;
    }

    await file.writeAsString(VscodeJsonMerge.encodePrettyJson(merged));
    Log.logDone(
      existing == null
          ? 'Wrote ${p.relative(path)}'
          : 'Updated ${p.relative(path)}',
    );
  }

  /// Decode a JSON/JSONC object, or null when the file is blank. Refuses to
  /// guess at malformed input — silently overwriting a user's config would
  /// lose their launch configurations.
  static Map<String, Object?>? _decodeJsonObject(String raw, String path) {
    if (raw.trim().isEmpty) return null;

    final Object? decoded;
    try {
      decoded = VscodeJsonMerge.parseJsonc(raw);
    } on FormatException catch (e) {
      throw XcrossError(
        '${p.relative(path)} is not valid JSON/JSONC (${e.message}) — '
        'fix it, then re-run `xcross ide vscode`',
      );
    }
    if (decoded is! Map) {
      throw XcrossError(
        '${p.relative(path)} must be a JSON object — '
        'fix it, then re-run `xcross ide vscode`',
      );
    }
    return {for (final e in decoded.entries) '${e.key}': e.value};
  }
}

/// Dart-Code spawns this as `dart <this file> debug_adapter`, so it must stay a
/// source file (the Dart VM cannot run xcross's AOT snapshot) and must write
/// NOTHING to stdout — that pipe carries DAP frames.
const String _shim = r'''
// GENERATED by `xcross ide vscode`. Do not edit — re-run the command instead.
import 'dart:io';

Future<void> main(List<String> args) async {
  // `flutter test` sessions arrive through the same customFlutterDapPath
  // setting; hand those to the real Flutter adapter. Non-xcross launch
  // configs are gated inside `xcross flutter dap` via the XCROSS env marker.
  if (args.contains('--test')) {
    final flutterRoot = Platform.environment['FLUTTER_ROOT'];
    if (flutterRoot == null) {
      stderr.writeln('xcross_dap: FLUTTER_ROOT is not set; '
          'cannot delegate a flutter test session.');
      exit(2);
    }
    final flutter = await Process.start(
      '$flutterRoot/bin/flutter',
      ['debug-adapter', ...args.where((a) => a != 'debug_adapter')],
      mode: ProcessStartMode.inheritStdio,
      environment: <ENVIRONMENT>,
      includeParentEnvironment: <INHERIT_PARENT>,
    );
    exit(await flutter.exitCode);
  }

  try {
    final dap = await Process.start(
      <XCROSS>,
      ['flutter', 'dap'],
      mode: ProcessStartMode.inheritStdio,
      environment: <ENVIRONMENT>,
      includeParentEnvironment: <INHERIT_PARENT>,
    );
    exit(await dap.exitCode);
  } on ProcessException catch (e) {
    stderr.writeln('xcross_dap: could not start xcross: ${e.message}\n'
        'Reinstall xcross, then re-run `xcross ide vscode`.');
    exit(2);
  }
}
''';
